Sketch parray fix
CadQuery/cadquery pull request #1005
Opened 2022-02-19 03:08 UTC by lorenzncode

* Start angle and rotation convention to be consistent with arc #1001
* Fix parray bug when used with push
* Return n locations for 360 degree array
* Fix n=1

With current PR changes:
```
s = cq.Sketch().parray(20, 20, -70, 8).circle(0.5)
```
![e1](https://user-images.githubusercontent.com/16394272/154783740-c1254027-b5ee-46ac-96e0-d44b0c1be08a.png)

```
s = cq.Sketch().parray(4, 0, 180, 6).rect(1, 0.5)
```

![e2](https://user-images.githubusercontent.com/16394272/154783752-f73c8b83-7c26-4c6d-b53b-765e689bc21c.png)

```
s = cq.Sketch().push([(5,5)]).parray(4, 20, 360, 6).rect(1, 0.5)
```

![e3](https://user-images.githubusercontent.com/16394272/154783760-b857c5c3-dd83-4d3f-bef6-3d10c2853db1.png)

2022-02-20 16:43 UTC, lorenzncode commented on cadquery/sketch.py
> +        if abs(remainder(da, 360)) < 1e-3:
Better to use standard `math.isclose()` here instead of `abs` less than?

2022-02-21 18:45 UTC, vincele commented on cadquery/sketch.py
> +                * el
pycodestyle issues a "W503 line break before binary operator"

2022-02-22 17:23 UTC, adam-urbanczyk requested changes

2022-02-22 17:23 UTC, adam-urbanczyk commented on cadquery/sketch.py
> +                    Vector(0, 0), Vector(0, 0, 1), (a1 + (angle * i)) * int(rotate)
I'd propose this for readability
```suggestion
                    Vector(0, 0), Vector(0, 0, 1), (a1 + (angle * i)) if rotate else 0
```

2022-02-22 17:23 UTC, adam-urbanczyk commented on cadquery/sketch.py
> +        if abs(remainder(da, 360)) < 1e-3:
```suggestion
        if abs(remainder(da, 360)) < 1e-6:
```

2022-02-24 17:22 UTC, jmwright approved these changes
Thanks @lorenzncode 

Is this ready to merge?

2022-02-24 23:31 UTC, lorenzncode commented
It's ready to merge unless any additional review changes are requested.  Regarding the following changes do let me know if there is an issue. 

1. Arg `a2` changed to `da`.  Initially I did not feel strongly about this part.  After testing I leaned toward making this consistent with `arc` as well.
   Consider distributing over a half circle:
    - `a2`: `parray(10, 70, 70+180, 6)`
    - `da`: `parray(10, 70, 180, 6)`

2. Distributing over a full circle - special handling was added to generate `n` requested locations.

2022-02-25 06:35 UTC, adam-urbanczyk commented
@lorenzncode LGTM!

2022-02-25 06:35 UTC, adam-urbanczyk approved these changes

2022-02-25 11:16 UTC, merged