Fix sketch solver line_point method relative/absolute mixup
CadQuery/cadquery pull request #1336
Opened 2023-05-20 16:02 UTC by voneiden

Closes #1127

2023-06-10 19:03 UTC, lorenzncode requested changes
The fix itself looks good.

There is an assert missing here in the tests: 
https://github.com/CadQuery/cadquery/blob/7143eadb8e69bd9c3cecdf28b3cb77e7eaf974c0/tests/test_sketch.py#L643

I'd suggest to add the assert to line 643.  It should be sufficient for testing the fix.

```py
    assert (midpoint - seg1.startPoint()).Length == approx(2)
```

I've added a comment regarding the new pytest with sketch "s8".  Since the sketch solver is experimental, it might be easier to keep the tests simple (skip adding the new test) since rework may be required later.  @voneiden , @adam-urbanczyk , if you disagree and want to keep the additional test please disregard that item.

2023-06-10 19:03 UTC, lorenzncode commented on tests/test_sketch.py
> +
This test may be redundant - can be removed.

2023-06-14 09:07 UTC, voneiden commented
There we go, verified that the assert is indeed enough to test this fix.

2023-06-16 02:40 UTC, lorenzncode approved these changes
Thanks @voneiden!

2023-06-16 06:33 UTC, voneiden commented
Was that an accidental wrong branch for your commit 62d2a4c @adam-urbanczyk ?

2023-06-16 06:37 UTC, adam-urbanczyk commented
It was on purpose - trying to fix appveyor

2023-06-17 08:50 UTC, adam-urbanczyk commented
Green, thanks @voneiden !

2023-06-17 08:50 UTC, merged