Sketch improvements
CadQuery/cadquery pull request #1633
Opened 2024-07-19 18:07 UTC by adam-urbanczyk

This should resolve #1614, #1575, #1511 and add special methods to `Sketch`.

2024-07-28 15:01 UTC, adam-urbanczyk commented
Quite some goodies, e.g.
```python
import cadquery as cq

s1 = cq.Sketch().rect(1,1).vertices().fillet(0.2).reset()
s2 = cq.Sketch().rect(0.5,0.5).vertices().fillet(0.1).reset()

s3 = s1 - s2

w = (
     cq.Workplane()
     .placeSketch(s1, s2.moved(z=1))
     .loft()
     .faces('>Z')
     .extrude(1)
     .faces('>Z').workplane()
     .eachpoint(s2.wires().offset(-0.1,mode='r').reset().val())
     .cutThruAll()
)

w.export('out.brep')
```

![afbeelding](https://github.com/user-attachments/assets/75f439e8-819d-4c65-a77a-6ab966a129fd)

2024-07-30 19:23 UTC, jmwright commented on cadquery/occ_impl/exporters/dxf.py
> +        :param s: CadQuery Workplane or shape
```suggestion
        :param s: CadQuery Workplane or Shape
```

2024-07-30 19:43 UTC, jmwright approved these changes
Thanks for all the work on this @adam-urbanczyk !

2024-08-03 20:24 UTC, lorenzncode requested changes
I've tested the new features (at least most of them).  It looks great with nice usability improvements too.  I found a few doc issues/typos.

2024-08-03 20:24 UTC, lorenzncode commented on tests/test_cadquery.py
> +
Not a must, but the `rarray` call on lines 5760, 5768, prompted me to open issue #1603.  These *could* be updated to set y spacing to zero for readability.

2024-08-20 06:17 UTC, adam-urbanczyk commented on cadquery/assembly.py
> +        elif exportType == "STL":
Opened #1648 to track this

2024-08-20 06:29 UTC, adam-urbanczyk commented
@lorenzncode I think I solved all the issues, could you take another look?

2024-08-21 00:12 UTC, lorenzncode approved these changes

2024-08-21 00:12 UTC, lorenzncode commented
Thanks @adam-urbanczyk !

2024-08-21 04:07 UTC, merged