Improve Inheriting Workplane Fluent Methods
CadQuery/cadquery pull request #677
Opened 2021-03-05 07:38 UTC by pavpen

* Updated `Workplane.workplane()`, `Workplane.copyWorkplane()`, `Workplane.newObject()` to return instances of a type that's based on the input parameters (such as `self`).
* Updated type hints to reflect that return types of fluent methods depend on the type of method arguments.
* Added a unit test to verify fluent methods in a derived class return instances of the derived class.

This is a pull request for issue #673.

2021-03-06 06:05 UTC, marcus7070 commented
AppVeyor is failing a single test on 3.6, `testOffset2D`:
```
self.assertEqual(s.solids().size(), 4)
E       AssertionError: 1 != 4
tests\test_cadquery.py:4093: AssertionError
```

That test passes in all other CI envs, including [Win 3.6 on Azure](https://dev.azure.com/cadquery/conda-packages/_build/results?buildId=1298&view=logs&j=8dfee29a-6c4b-5791-c9fb-5c4b86e62ffc&t=dca0eed6-a0fb-5148-1f1c-eb3f6b259679&l=655). @adam-urbanczyk this looks super weird, you might want to re-run that test? I don't have the permissions.

Although honestly, if it goes away after re-running that's going to be just as confusing. It's not like it's a network error...

2021-03-09 05:05 UTC, pavpen commented
Hm. Yeah, these tests pass for me with Python 3.6.13 and 3.9.2 on Windows. It would be useful if someone is able to reproduce this error.

I can also push a whitespace change to force a re-run of the appveyor job. Or, is there a way to re-run it manually?

2021-03-09 05:17 UTC, marcus7070 commented
@adam-urbanczyk should have the permissions to re-run it manually, but he's busy at the moment. so feel free to do the whitespace change. Here is a (hopefully semi-permanent) link to the failing job for posterity: https://ci.appveyor.com/project/adam-urbanczyk/cadquery-icqj5/builds/38091458/job/k9pg21fnvqup9be5

2021-03-09 06:45 UTC, adam-urbanczyk commented
If all fails, you can always close an reopen to trigger CI

2021-03-09 17:04 UTC, adam-urbanczyk requested changes
One change request, otherwise looks good!

2021-03-09 22:39 UTC, jmwright approved these changes
I think once the requested change is done this will be ready to merge.  Thanks @pavpen !

2021-03-10 17:55 UTC, pavpen commented on cadquery/cq.py
> +WorkplaneT = TypeVar("WorkplaneT", bound="Workplane")
Done.

2021-03-11 21:15 UTC, adam-urbanczyk approved these changes

2021-03-12 06:34 UTC, adam-urbanczyk commented
Thanks @pavpen !

2021-03-12 06:34 UTC, merged

2021-03-12 22:59 UTC, pavpen commented
Thanks for the help! If you can figure out the differences between execution environments, it could help track the causes of the flaky unit tests.